"""
Decision-Codes — stabile Bezeichner für alle möglichen Entscheidungen.

Codes sind stabil über Releases: nur addieren, nie umbenennen.
"""

# R1 Profitabilität
START_R1_SURPLUS_OK = "START_R1_SURPLUS_OK"
THROTTLE_R1_SURPLUS_THROTTLE = "THROTTLE_R1_SURPLUS_THROTTLE"
NOOP_R1_INSUFFICIENT_SURPLUS = "NOOP_R1_INSUFFICIENT_SURPLUS"
NOOP_R1_PRICE_TOO_HIGH = "NOOP_R1_PRICE_TOO_HIGH"

# R1 SoC-Band-Strategie (strategy="soc_band", reale Produktiv-Steuerung)
STOP_R1_SOC_RESERVE_STOP = "STOP_R1_SOC_RESERVE_STOP"
NOOP_R1_SOC_RESERVE_STOP = "NOOP_R1_SOC_RESERVE_STOP"  # SEMI-Modus
NOOP_R1_SOC_HOLD = "NOOP_R1_SOC_HOLD"
NOOP_R1_SOC_HOLD_PV = "NOOP_R1_SOC_HOLD_PV"
THROTTLE_R1_ECO = "THROTTLE_R1_ECO"
START_R1_STANDARD = "START_R1_STANDARD"
START_R1_SUPER = "START_R1_SUPER"
NOOP_NIGHT_BLOCK = "NOOP_NIGHT_BLOCK"

# R2 Autarkie
STOP_R2_SOC_HARD_MIN = "STOP_R2_SOC_HARD_MIN"
NOOP_R2_SOC_SOFT_MIN = "NOOP_R2_SOC_SOFT_MIN"
STOP_R2_GRID_IMPORT_EXCEEDED = "STOP_R2_GRID_IMPORT_EXCEEDED"

# R3 Safety (nie überstimmbar)
STOP_R3_OVERTEMP = "STOP_R3_OVERTEMP"
STOP_R3_COMM_TIMEOUT = "STOP_R3_COMM_TIMEOUT"

# R4 Forecast
NOOP_R4_FORECAST_PV_INSUFFICIENT = "NOOP_R4_FORECAST_PV_INSUFFICIENT"
NOOP_R4_FORECAST_PRICE_SPIKE = "NOOP_R4_FORECAST_PRICE_SPIKE"

# R5 Stabilität
NOOP_R5_DEADBAND_ACTIVE = "NOOP_R5_DEADBAND_ACTIVE"
NOOP_R5_MIN_RUNTIME_NOT_REACHED = "NOOP_R5_MIN_RUNTIME_NOT_REACHED"
NOOP_R5_MIN_PAUSE_NOT_REACHED = "NOOP_R5_MIN_PAUSE_NOT_REACHED"

# Autonomie-Modi
NOOP_MANUAL_MODE = "NOOP_MANUAL_MODE"

ALL_CODES = {
    START_R1_SURPLUS_OK,
    THROTTLE_R1_SURPLUS_THROTTLE,
    NOOP_R1_INSUFFICIENT_SURPLUS,
    NOOP_R1_PRICE_TOO_HIGH,
    STOP_R1_SOC_RESERVE_STOP,
    NOOP_R1_SOC_RESERVE_STOP,
    NOOP_R1_SOC_HOLD,
    NOOP_R1_SOC_HOLD_PV,
    THROTTLE_R1_ECO,
    START_R1_STANDARD,
    START_R1_SUPER,
    NOOP_NIGHT_BLOCK,
    STOP_R2_SOC_HARD_MIN,
    NOOP_R2_SOC_SOFT_MIN,
    STOP_R2_GRID_IMPORT_EXCEEDED,
    STOP_R3_OVERTEMP,
    STOP_R3_COMM_TIMEOUT,
    NOOP_R4_FORECAST_PV_INSUFFICIENT,
    NOOP_R4_FORECAST_PRICE_SPIKE,
    NOOP_R5_DEADBAND_ACTIVE,
    NOOP_R5_MIN_RUNTIME_NOT_REACHED,
    NOOP_R5_MIN_PAUSE_NOT_REACHED,
    NOOP_MANUAL_MODE,
}
