"""
Decision-Codes — stabile Bezeichner für alle möglichen Entscheidungen.

Codes sind stabil über Releases: nur addieren, nie umbenennen.
"""

# R1 Profitabilität
START_R1_SURPLUS_OK = "START_R1_SURPLUS_OK"
NOOP_R1_INSUFFICIENT_SURPLUS = "NOOP_R1_INSUFFICIENT_SURPLUS"
NOOP_R1_PRICE_TOO_HIGH = "NOOP_R1_PRICE_TOO_HIGH"

# R2 Autarkie
STOP_R2_SOC_HARD_MIN = "STOP_R2_SOC_HARD_MIN"
NOOP_R2_SOC_SOFT_MIN = "NOOP_R2_SOC_SOFT_MIN"
STOP_R2_GRID_IMPORT_EXCEEDED = "STOP_R2_GRID_IMPORT_EXCEEDED"

# R3 Safety (nie überstimmbar)
STOP_R3_OVERTEMP = "STOP_R3_OVERTEMP"
STOP_R3_COMM_TIMEOUT = "STOP_R3_COMM_TIMEOUT"

# R4 Forecast
NOOP_R4_FORECAST_PV_INSUFFICIENT = "NOOP_R4_FORECAST_PV_INSUFFICIENT"
NOOP_R4_FORECAST_PRICE_SPIKE = "NOOP_R4_FORECAST_PRICE_SPIKE"

# R5 Stabilität
NOOP_R5_DEADBAND_ACTIVE = "NOOP_R5_DEADBAND_ACTIVE"
NOOP_R5_MIN_RUNTIME_NOT_REACHED = "NOOP_R5_MIN_RUNTIME_NOT_REACHED"
NOOP_R5_MIN_PAUSE_NOT_REACHED = "NOOP_R5_MIN_PAUSE_NOT_REACHED"

ALL_CODES = {
    START_R1_SURPLUS_OK,
    NOOP_R1_INSUFFICIENT_SURPLUS,
    NOOP_R1_PRICE_TOO_HIGH,
    STOP_R2_SOC_HARD_MIN,
    NOOP_R2_SOC_SOFT_MIN,
    STOP_R2_GRID_IMPORT_EXCEEDED,
    STOP_R3_OVERTEMP,
    STOP_R3_COMM_TIMEOUT,
    NOOP_R4_FORECAST_PV_INSUFFICIENT,
    NOOP_R4_FORECAST_PRICE_SPIKE,
    NOOP_R5_DEADBAND_ACTIVE,
    NOOP_R5_MIN_RUNTIME_NOT_REACHED,
    NOOP_R5_MIN_PAUSE_NOT_REACHED,
}
