[mypy]
strict = True
ignore_missing_imports = True
exclude = src/ha/config/custom_components/

[mypy-pymodbus.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-yaml]
ignore_missing_imports = True

[mypy-src.ui.api]
warn_unused_ignores = False
